function [nn_params]=train_nn(initial_nn_params,lambda,train_x,train_y,input_layer_size,...
                 hidden_layer_size1, hidden_layer_size2,num_labels)
  
   options = optimset('MaxIter', 600);%optimset('MaxIter', 3000)--迭代次数为3000
   %结构体初始化，初始化参数为具体值
                                       %计算初始的误差函数，含有正则化項的误差函数
   debug_J= nnCostFunction(initial_nn_params, input_layer_size, ...
                hidden_layer_size1, hidden_layer_size2,num_labels, train_x,train_y,lambda);
   costFunction = @(p) nnCostFunction(p, ...
                                   input_layer_size, ...
                                   hidden_layer_size1, ...
                                   hidden_layer_size2, ...
                                   num_labels, train_x, train_y, lambda);  
   %调用函数fmincg去寻找最优解，得到最优解的参数nn_params,并返回参数
   [nn_params, cost] = fmincg(costFunction, initial_nn_params, options);  
end